version: '3.8'

services:
  app:
    platform: linux/amd64 # Need this if on M1 macbook
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - LOG_LEVEL=info
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
